# Generated by Django 2.0.7 on 2018-07-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('music', 'Music'), ('comedy', 'Comedy'), ('poetry', 'Poetry')], max_length=10)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('signup_time', models.TimeField(blank=True, null=True)),
                ('signup_info', models.TextField(blank=True, null=True)),
                ('included_gear', models.TextField(blank=True, null=True)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_address', models.CharField(max_length=100)),
                ('venue_city', models.CharField(max_length=100)),
                ('venue_state', models.CharField(max_length=100)),
                ('venue_country', models.CharField(max_length=100)),
                ('venue_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('venue_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(to='api.ImageAsset')),
                ('thumb_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumb_image', to='api.ImageAsset')),
            ],
        ),
    ]
