# Generated by Django 2.0.7 on 2018-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='api.ImageAsset'),
        ),
    ]
