# Generated by Django 2.0.7 on 2018-07-20 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20180720_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_performer', models.BooleanField(default=False)),
                ('is_host', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ImageAsset')),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='stage',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.ImageAsset'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Stage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stages_hosted_at',
            field=models.ManyToManyField(blank=True, related_name='stages_hosted_at', to='api.Stage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stages_performed_at',
            field=models.ManyToManyField(blank=True, related_name='stages_performed_at', to='api.Stage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
